name: netflix_clone
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.18.0-241.0.dev <3.0.0"

dependencies:
  bloc: ^8.1.2
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: 0.10.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  injectable: ^1.5.3
  intl: 0.17.0
  json_annotation: ^4.8.1
  json_serializable: ^6.3.1
  lottie: ^1.4.2
  readmore: ^2.2.0
  share_plus: 4.0.3
  smooth_page_indicator: ^1.0.0+2
  video_player: 2.3.0

flutter_icons:
  android: true
  image_path: "assets/images/netflix_logo.png"

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/splashLogo/data.json
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/Netflix-Brand-Logo.png
